"area: lib":
  - changed-files:
      - any-glob-to-any-file:
          - src/**

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - README.md
          - CHANGELOG.md
          - CONTRIBUTING.md
          - SECURITY.md
          - CODE_OF_CONDUCT.md
          - LICENSE

ci:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - .pre-commit-config.yaml

build:
  - changed-files:
      - any-glob-to-any-file:
          - Makefile
          - rustfmt.toml
          - deny.toml

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - Cargo.toml
          - Cargo.lock
